services:
  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
    environment:
      ORIGIN: ${APP_ORIGIN}
      DATABASE_URL: ${DATABASE_URL}
  database:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongodb:
