on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to server
        run: |
          cd ..
          git pull origin master
          docker compose up database -d
          docker compose up -d
          echo "Successfully deployed server"